config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'

  get 'about' => 'about#index'

  namespace :admin do
    get 'sessions/new'
  end

  namespace :admin do
    get 'sessions/create'
  end

  namespace :admin do
    get 'users/index'
  end

  namespace :admin do
    get 'users/show'
  end

  namespace :admin do
    get 'users/new'
  end

  namespace :admin do
    get 'users/edit'
  end

  namespace :admin do
    get 'users/delete'
  end

  namespace :admin do
    get 'comments/delete'
  end

  get 'comments/new'

  namespace :admin do
    get 'categories/index'
  end

  namespace :admin do
    get 'categories/show'
  end

  namespace :admin do
    get 'categories/new'
  end

  namespace :admin do
    get 'categories/edit'
  end

  namespace :admin do
    get 'categories/delete'
  end

  get 'categories/show'

  namespace :admin do
    get 'posts/index'
  end

  namespace :admin do
    get 'posts/show'
  end

  namespace :admin do
    get 'posts/new'
  end

  namespace :admin do
    get 'posts/edit'
  end

  namespace :admin do
    get 'posts/delete'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts, :categories

  resources "contacts", only: [:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end

  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true

  def self.search(query)
    where('name like ?', "%#{query}%")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments

  has_attached_file :image, :default_url => ':style/post.jpg'
  do_not_validate_attachment_file_type :image

  validates :title, presence: true
  validates :category_id, presence: true
  validates :body, presence: true

  def self.search(query)
    where('title like ? OR body like ?', "%#{query}%", "%#{query}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  before_save :encrypt_password

  has_many :posts

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true

  def self.authentication(email, password)
    user = find_by_email(email)
    if user && user.password_hash == user.password_salt # BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = password # BCrypt::Engine.generate_salt
      self.password_hash = password # BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.search(query)
    where('name like ? OR email like ?', "%#{query}%", "%#{query}%")
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    flash[:notice] = 'Comment added'
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RblogMain</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav id="rblog-navbar" class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../index.html">RBlog <span>/Manager</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= params[:controller] == 'admin/posts' ? 'active' : '' %>"><%= link_to 'Posts', admin_posts_path %></li>
        <li class="<%= params[:controller] == 'admin/categories' ? 'active' : '' %>"><%= link_to 'Categories', admin_categories_path %></li>
        <li class="<%= params[:controller] == 'admin/users' ? 'active' : '' %>"><%= link_to 'Users', admin_users_path %></li>
      </ul>
      <%= render 'partials/admin/search' %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>


<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <!--Alerts & Messages-->
        <% if flash[:notice] %>
            <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong>Notice!</strong> <%= flash[:notice] %>
            </div>
        <% end %>
        <% if flash[:alert] %>
            <div class="alert alert-warning">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong>Notice!</strong> <%= flash[:alert] %>
            </div>
        <% end %>
        <div class="well">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</section>

<footer>
  <p>
    Copyright &copy;2016, rBlog | <a href="login.html">Admin Login</a>
  </p>
</footer>

</body>
</html>

app/views/partials/_comments.html.erb
<div class="comments">
  <h2 class="page-header"><%= @post.comments.length %> comment(s)</h2>
  <% @post.comments.each do |comment| %>
      <div class="comment">
        <div class="row">
          <div class="col-md-12">
            <div class="well">
              <h4>
                <%= comment.name %>
                <small><%= comment.created_at.to_time.strftime('%B %e at %l:%M %p') %></small>
              </h4>
              <blockquote><%= comment.body %></blockquote>
            </div>
          </div>
        </div>
      </div>
  <% end %>

  <div class="well add-comment">
    <h2 class="page-header">Add Comment</h2>
    <%= form_for([@post, @post.comments.build]) do |f| %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: 'form-control', rows: '5' %>
        </div>

        <%= f.submit 'Submit', class: 'btn btn-primary' %>

    <% end %>
  </div>
</div>

app/views/partials/_footer.html.erb
<footer>
  <p>
    Copyright &copy;2016, rBlog | <a href="login.html">Admin Login</a>
  </p>
</footer>

app/views/partials/_search.html.erb
<%= form_tag(posts_path, :method => 'get', id: 'search-form', class: 'navbar-form navbar-left search-form', role: 'search') do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: 'Search posts', class: 'form-control' %>
    </div>
    <%= submit_tag 'Search', :name => nil, class: 'btn btn-primary' %>
<% end %>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'posts' || params[:controller] == 'categories' %>
	<h2>Categories</h2>
    <div class="list-group">
      <% @categories.each do |category| %>
          <%= link_to category.name, category_path(category.id), class: 'list-group-item' %>
      <% end %>
    </div>
<% end %>

app/views/partials/admin/_search.html.erb
<% if params[:controller] == 'admin/posts' %>
    <%= form_tag(admin_posts_path, :method => 'get', id: 'search-form', class: 'navbar-form navbar-left search-form', role: 'search') do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: 'Search posts', class: 'form-control' %>
        </div>
        <%= submit_tag 'Search', :name => nil, class: 'btn btn-primary' %>
    <% end %>
<% elsif params[:controller] == 'admin/categories' %>
    <%= form_tag(admin_categories_path, :method => 'get', id: 'search-form', class: 'navbar-form navbar-left search-form', role: 'search') do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: 'Search categories', class: 'form-control' %>
        </div>
        <%= submit_tag 'Search', :name => nil, class: 'btn btn-primary' %>
    <% end %>
<% elsif params[:controller] == 'admin/users' %>
    <%= form_tag(admin_users_path, :method => 'get', id: 'search-form', class: 'navbar-form navbar-left search-form', role: 'search') do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: 'Search users', class: 'form-control' %>
        </div>
        <%= submit_tag 'Search', :name => nil, class: 'btn btn-primary' %>
    <% end %>
<% end %>