config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'

  get 'about' => 'about#index'

  namespace :admin do
    get 'sessions/new'
  end

  namespace :admin do
    get 'sessions/create'
  end

  namespace :admin do
    get 'users/index'
  end

  namespace :admin do
    get 'users/show'
  end

  namespace :admin do
    get 'users/new'
  end

  namespace :admin do
    get 'users/edit'
  end

  namespace :admin do
    get 'users/delete'
  end

  namespace :admin do
    get 'comments/delete'
  end

  get 'comments/new'

  namespace :admin do
    get 'categories/index'
  end

  namespace :admin do
    get 'categories/show'
  end

  namespace :admin do
    get 'categories/new'
  end

  namespace :admin do
    get 'categories/edit'
  end

  namespace :admin do
    get 'categories/delete'
  end

  get 'categories/show'

  namespace :admin do
    get 'posts/index'
  end

  namespace :admin do
    get 'posts/show'
  end

  namespace :admin do
    get 'posts/new'
  end

  namespace :admin do
    get 'posts/edit'
  end

  namespace :admin do
    get 'posts/delete'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts, :categories

  resources "contacts", only: [:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end

  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true

  def self.search(query)
    where('name like ?', "%#{query}%")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments

  has_attached_file :image, :default_url => ':style/post.jpg'
  do_not_validate_attachment_file_type :image

  validates :title, presence: true
  validates :category_id, presence: true
  validates :body, presence: true

  def self.search(query)
    where('title like ? OR body like ?', "%#{query}%", "%#{query}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  before_save :encrypt_password

  has_many :posts

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true

  def self.authentication(email, password)
    user = find_by_email(email)
    if user && user.password_hash == user.password_salt # BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = password # BCrypt::Engine.generate_salt
      self.password_hash = password # BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.search(query)
    where('name like ? OR email like ?', "%#{query}%", "%#{query}%")
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    if params[:search]
      @users = User.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @users = User.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User added.'
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = 'User updated'
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'User deleted'
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    flash[:notice] = 'Comment added'
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/users/_form.html.erb
<!--Check for errors-->
<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
        <!--Show them-->
        <div class="alert alert-danger">
          <%= msg %>
        </div>
    <% end %>
<% end %>

<div class="form-group">
  <%= f.input :name, input_html: {class: 'form-control'} %>
</div>

<div class="form-group">
  <%= f.input :email, input_html: {class: 'form-control'} %>
</div>

<div class="form-group">
  <%= f.input :password, input_html: {class: 'form-control'} %>
</div>

<div class="form-group">
  <%= f.input :password_confirmation, input_html: {class: 'form-control'} %>
</div>

app/views/admin/users/delete.html.erb
<h1>Admin::Users#delete</h1>
<p>Find me in app/views/admin/users/delete.html.erb</p>

app/views/admin/users/edit.html.erb
<h2>Add new user</h2>
<%= simple_form_for [:admin, @user] do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <%= f.button :submit, class: 'btn btn-primary' %>

    <%= link_to 'Cancel', admin_users_path, class: 'btn btn-default' %>

<% end %>

app/views/admin/users/index.html.erb
<div class="page-header">
  <h1>Manage Users <%= link_to 'Create New', new_admin_user_path, class: 'btn btn-success pull-right' %></h1>
</div>

<% if @users.exists? %>

    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Created</th>
          <th>Updated</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.created_at %></td>
              <td><%= user.updated_at %></td>
              <td>
                <%= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-primary' %>
                <%= link_to 'Delete', admin_user_path(user), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <%= will_paginate @users %>

<% else %>

    <p>There are no users</p>

<% end %>

app/views/admin/users/new.html.erb
<h2>Add new user</h2>
<%= simple_form_for [:admin, @user] do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <%= f.button :submit, class: 'btn btn-primary' %>

    <%= link_to 'Cancel', admin_users_path, class: 'btn btn-default' %>

<% end %>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>